version: "3"

services:
  grpc-server:
    image: grpc-server:latest
    container_name: "grpc-server"
    build:
      context: grpc-server
    ports:
      - "8081:8081"
      - "58081:58081"
    networks:
      - infra_net

  grpc-client:
    image: grpc-client:latest
    container_name: "grpc-client"
    build:
      context: grpc-client
    environment:
      GRPC_SERVER_HOST: grpc-server
      GRPC_SERVER_PORT: 58081
    ports:
      - "8082:8082"
    networks:
      - infra_net
    depends_on:
      - grpc-server

  grpc_gateway:
    image: dev-golang:latest
    container_name: grpc_gateway
    build:
      context: grpc-gateway
    working_dir: /app
    volumes:
      - ./grpc-gateway:/app
    networks:
      - infra_net
    ports:
      - "8085:8085"
    command: "go run main.go"


networks:
  infra_net:
    driver: bridge
    external: true