@startuml

title "DIAGRAM\nGRPC Client\n\n"

skinparam sequence {
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Impact
    ParticipantFontSize 17
    ParticipantFontColor white
    ActorFontColor DeepSkyBlueA9DCDF
    ActorFontColor Black
    ActorFontSize 17
    ActorFontName Aapex
}

actor User
box "\nBACKEND\n\n"
    participant "GRPC Client" as grpcClient  #darkblue
    participant "GRPC Server" as grpcServer  #283747
end box


group Performing addition calculation.
    autonumber 1
    User -> grpcClient++: POST /v1/calculator/add <<HTTP>>
    grpcClient -> grpcServer++: Request calculation <<GRPC>>
    grpcServer -> grpcServer: Internal process <<GRPC>>
    grpcServer --> grpcClient: Calculation answer <<GRPC>>
    deactivate grpcServer

    grpcClient --> User: Calculation answer <<HTTP>>
    deactivate grpcClient
end

footer \n**Page** %page% **of** %lastpage%\n**Author**: Hemicharly Thiago\nRendered with PlantUML Version: **%version()**

@enduml