spring:
  application:
    name: grpc-client

server:
  port: 8081

grpc-client:
  calculator:
    host: localhost
    port: 9080

springdoc:
  api-docs:
    enabled: true
    path: /swagger-doc/api
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-doc/index.html
  override-with-generic-response: false


logging:
  pattern:
    console: "{ \"datetime\": \"%d{yyyy-MM-dd HH:mm:ss.SSS}\", \"level\": \"%level\", \"traceId\": \"%mdc{traceId}\", \"spanId\": \"%mdc{spanId}\", \"thread\": \"%thread\", \"class\": \"%c{2.}\", \"message\": \"%m\"}%n"

