name: CI - Update Develop
on:
  push:
    branches: [ main ]

jobs:
  update-develop:
    name: update-develop
    runs-on: ubuntu-latest
    steps:
      - name: 'Update Branch Develop'
        uses: Logerfo/gitflow-action@0.0.5
        with:
          github-token: ${{ secrets.GITACTION_FLOW_TOKEN }}
          dev: develop
          master: main
          label: gitflow
          auto-merge: true
          require-merge: false
