name: CI - Update Develop
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-develop:
    name: update-develop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Update Branch Develop'
        uses: Logerfo/gitflow-action@0.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dev: develop
          master: main
          label: gitflow
          auto-merge: true
          require-merge: false
