name: CI - Update Develop
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-develop:
    name: update-develop
    runs-on: ubuntu-18.04
    steps:
      - name: 'Update Branch Develop'
        uses: Logerfo/gitflow-action@0.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dev: develop
          master: main
          label: gitflow
          auto-merge: true
          require-merge: false
